# Generated by Django 4.2 on 2024-05-22 05:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="WeatherData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("temperature", models.FloatField()),
                ("humidity", models.FloatField()),
                ("prescipitation", models.FloatField()),
                ("wind_speed", models.FloatField()),
                ("uv", models.FloatField()),
                ("pressure", models.FloatField()),
                ("evapotranspiration", models.FloatField()),
                ("temperation_soil", models.FloatField()),
                ("couverture", models.FloatField()),
                ("date", models.DateField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name="WeatherPredict",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("temperature", models.FloatField()),
                ("humidity", models.FloatField()),
                ("prescipitation", models.FloatField()),
                ("wind_speed", models.FloatField()),
                ("uv", models.FloatField()),
                ("pressure", models.FloatField()),
                ("evapotranspiration", models.FloatField()),
                ("temperation_soil", models.FloatField()),
                ("couverture", models.FloatField()),
                ("date", models.DateField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
