# Generated by Django 4.2 on 2024-05-22 10:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("weather", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="weatherdata",
            old_name="prescipitation",
            new_name="precipitation",
        ),
    ]
