# Generated by Django 4.2 on 2024-05-22 12:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("weather", "0002_rename_prescipitation_weatherdata_precipitation"),
    ]

    operations = [
        migrations.RenameField(
            model_name="weatherpredict",
            old_name="prescipitation",
            new_name="precipitation",
        ),
    ]
