# Generated by Django 4.2 on 2024-05-23 04:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("weather", "0003_rename_prescipitation_weatherpredict_precipitation"),
    ]

    operations = [
        migrations.AddField(
            model_name="weatherpredict",
            name="rose",
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="weatherdata",
            name="date",
            field=models.DateField(
                blank=True, default=datetime.datetime(2024, 5, 23, 5, 49, 55, 11773)
            ),
        ),
        migrations.AlterField(
            model_name="weatherpredict",
            name="date",
            field=models.DateField(
                blank=True, default=datetime.datetime(2024, 5, 23, 5, 49, 55, 12773)
            ),
        ),
    ]
