# Generated by Django 4.2 on 2024-05-23 08:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("weather", "0004_weatherpredict_rose_alter_weatherdata_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="weatherdata",
            name="couverture",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="weatherdata",
            name="date",
            field=models.DateField(
                blank=True, default=datetime.datetime(2024, 5, 23, 9, 34, 33, 390491)
            ),
        ),
        migrations.AlterField(
            model_name="weatherdata",
            name="evapotranspiration",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="weatherdata",
            name="humidity",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="weatherdata",
            name="pressure",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="weatherdata",
            name="temperation_soil",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="weatherdata",
            name="temperature",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="weatherdata",
            name="uv",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="weatherdata",
            name="wind_speed",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="weatherpredict",
            name="couverture",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="weatherpredict",
            name="date",
            field=models.DateField(
                blank=True, default=datetime.datetime(2024, 5, 23, 9, 34, 33, 391491)
            ),
        ),
        migrations.AlterField(
            model_name="weatherpredict",
            name="evapotranspiration",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="weatherpredict",
            name="humidity",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="weatherpredict",
            name="pressure",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="weatherpredict",
            name="rose",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="weatherpredict",
            name="temperation_soil",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="weatherpredict",
            name="temperature",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="weatherpredict",
            name="uv",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="weatherpredict",
            name="wind_speed",
            field=models.IntegerField(),
        ),
    ]
