# Generated by Django 4.2 on 2024-05-23 08:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "weather",
            "0005_alter_weatherdata_couverture_alter_weatherdata_date_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="weatherdata",
            name="date",
            field=models.DateField(
                blank=True, default=datetime.datetime(2024, 5, 23, 9, 55, 50, 541661)
            ),
        ),
        migrations.AlterField(
            model_name="weatherdata",
            name="precipitation",
            field=models.DecimalField(decimal_places=2, max_digits=2),
        ),
        migrations.AlterField(
            model_name="weatherpredict",
            name="date",
            field=models.DateField(
                blank=True, default=datetime.datetime(2024, 5, 23, 9, 55, 50, 541661)
            ),
        ),
        migrations.AlterField(
            model_name="weatherpredict",
            name="precipitation",
            field=models.DecimalField(decimal_places=2, max_digits=2),
        ),
    ]
