# Generated by Django 4.2 on 2024-05-23 13:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("weather", "0006_alter_weatherdata_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="weatherdata",
            name="couverture",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="weatherdata",
            name="date",
            field=models.DateField(
                blank=True, default=datetime.datetime(2024, 5, 23, 14, 32, 14, 102159)
            ),
        ),
        migrations.AlterField(
            model_name="weatherdata",
            name="evapotranspiration",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="weatherdata",
            name="humidity",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="weatherdata",
            name="precipitation",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="weatherdata",
            name="pressure",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="weatherdata",
            name="temperation_soil",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="weatherdata",
            name="temperature",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="weatherdata",
            name="uv",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="weatherdata",
            name="wind_speed",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="weatherpredict",
            name="couverture",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="weatherpredict",
            name="date",
            field=models.DateField(
                blank=True, default=datetime.datetime(2024, 5, 23, 14, 32, 14, 103159)
            ),
        ),
        migrations.AlterField(
            model_name="weatherpredict",
            name="evapotranspiration",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="weatherpredict",
            name="humidity",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="weatherpredict",
            name="precipitation",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="weatherpredict",
            name="pressure",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="weatherpredict",
            name="rose",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="weatherpredict",
            name="temperation_soil",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="weatherpredict",
            name="temperature",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="weatherpredict",
            name="uv",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="weatherpredict",
            name="wind_speed",
            field=models.FloatField(),
        ),
    ]
